# Generated by Django 6.1.1 on 2026-09-25 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='vendas.venda'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['produto', 'data_validade'], name='lotes_produto_b9987d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['-data'], name='movimentaco_data_36fd65_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['tipo', '-data'], name='movimentaco_tipo_6a3450_idx'),
        ),
    ]
