# Generated by Django 6.1.1 on 2026-09-25 02:09

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categorias',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nome'), name='categoria_nome_unico_ci')],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('volume', models.CharField(blank=True, max_length=30)),
                ('peso', models.CharField(blank=True, max_length=30)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='margem de lucro (%)')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('preco_venda', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('estoque_minimo', models.PositiveIntegerField(default=5)),
                ('estoque_maximo', models.PositiveIntegerField(default=100)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.categoria')),
            ],
            options={
                'db_table': 'produtos',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['ativo', 'nome'], name='produtos_ativo_f9c320_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('estoque_maximo__gte', models.F('estoque_minimo'))), name='produto_estoque_max_gte_min'), models.CheckConstraint(condition=models.Q(('preco_custo__gte', 0)), name='produto_preco_custo_nao_negativo'), models.CheckConstraint(condition=models.Q(('margem_lucro__gte', 0)), name='produto_margem_nao_negativa')],
            },
        ),
    ]
