# Generated by Django 6.1.1 on 2026-09-25 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome de usuário')),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador')], default='operador', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=255, verbose_name='senha')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['nome'],
            },
        ),
    ]
